### ISSUE TITLE
[Bug]: Node-red crashes on a restart with an error that "z-wave driver" is not ready (see paste of logs from NOde-red below)

### ISSUE THREAD

**Issue by ReziioAdmin** [zwave-js/node-red-contrib-zwave-js#275]
### What happened?

I have noticed this happening  on a few different Hubs in the past few weeks.  the Zwave interface becomes unresponsive and then Node-Red dives into a restart.  Most times it eventually recovers but I have one Hub right now that will just not get past the "uncaught error".

I am using a Zooz 700 Z-wave dongle.  One possibility is that the firmware is 7.17 and the latest version is 7.18.

### How to reproduce?

Please list steps to reproduce. If the problem is hardware-specific, please list which devices are affected.

### Version

8.0

### Node-RED Version

3.0.2

### What hardware are you seeing the problem on?

Other Linux

### Relevant Z-Wave-JS log as a text file

May 02 20:51:12 rosedale-apt-multi-N200 Node-RED[2746]: 2 May 20:51:12 - [error] ZWaveError: The controller is not yet ready! (ZW0103)
May 02 20:51:12 rosedale-apt-multi-N200 Node-RED[2746]:     at Driver.get controller [as controller] (/home/pi/.node-red/node_modules/zwave-js/src/lib/driver/Driver.ts:708:10)
May 02 20:51:12 rosedale-apt-multi-N200 Node-RED[2746]:     at Driver.shouldDiscardCC (/home/pi/.node-red/node_modules/zwave-js/src/lib/driver/Driver.ts:3607:21)
May 02 20:51:12 rosedale-apt-multi-N200 Node-RED[2746]:     at Driver.serialport_onData (/home/pi/.node-red/node_modules/zwave-js/src/lib/driver/Driver.ts:2895:14)
May 02 20:51:12 rosedale-apt-multi-N200 systemd[1]: nodered.service: Main process exited, code=exited, status=1/FAILURE
May 02 20:51:12 rosedale-apt-multi-N200 systemd[1]: nodered.service: Failed with result 'exit-code'.

**Comment by marcus-j-davies** [comment]
Thanks @ReziioAdmin,

Can you provide a ZWave JS log? you can do this on the controller node, set it to `Debug` on the file output.
The logfile will be in `/home/pi/.node-red`

This will provide me with a full list of events, from the driver starting up, to the Node RED crash you have detailed from the system log.

8.1.0 was released yesterday, that came with a new driver version (a few versions ahead of what 8.0 come with), so not sure if its worth trying your luck doing that first? else attach that log file as is, it has some critical debug information inside of it.

**Comment by ReziioAdmin** [comment]
Marcus

I upgraded to 8.1 and upgraded firmware on the Zooz stick to latest version.  I though this solved the issue as the hub booted back up fine with no errors.  I just logged in now to set up logging and when I deployed the error returned.

Can I DM you the log file pls - there is probably a few things in the log file that I wouldnt want to be publicly available

**Comment by ReziioAdmin** [comment]
NVM previous comment.  I was looking at the wrong log file.  Here is the zwave-js log.  
[zwave-js.log](https://github.com/zwave-js/node-red-contrib-zwave-js/files/11391980/zwave-js.log)

**Comment by marcus-j-davies** [comment]
@AlCalzone,
Do you have any idea what could be causing an unhandled exception? is this 700 specific?
The log doesn't show anything of interest (to me 😅 ), but the below does from the system log.

```
May 02 20:51:12 rosedale-apt-multi-N200 Node-RED[2746]: 2 May 20:51:12 - [error] ZWaveError: The controller is not yet ready! (ZW0103)
May 02 20:51:12 rosedale-apt-multi-N200 Node-RED[2746]:     at Driver.get controller [as controller] (/home/pi/.node-red/node_modules/zwave-js/src/lib/driver/Driver.ts:708:10)
May 02 20:51:12 rosedale-apt-multi-N200 Node-RED[2746]:     at Driver.shouldDiscardCC (/home/pi/.node-red/node_modules/zwave-js/src/lib/driver/Driver.ts:3607:21)
May 02 20:51:12 rosedale-apt-multi-N200 Node-RED[2746]:     at Driver.serialport_onData (/home/pi/.node-red/node_modules/zwave-js/src/lib/driver/Driver.ts:2895:14)
May 02 20:51:12 rosedale-apt-multi-N200 systemd[1]: nodered.service: Main process exited, code=exited, status=1/FAILURE
May 02 20:51:12 rosedale-apt-multi-N200 systemd[1]: nodered.service: Failed with result 'exit-code'.
```

Context of issue above of course.

**Comment by AlCalzone** [comment]
This should already be fixed in the latest driver release.

**Comment by AlCalzone** [comment]
Weird, the logs do show 10.16.0, but the line numbers in the error log line up with where those are in 10.15.0 🤔

**Comment by marcus-j-davies** [comment]
@ReziioAdmin 

Lets update the driver again.

 - Stop Node RED
 - Within `/home/pi/.node-red` run `npm update zwave-js`
 - Then run `npm list zwave-js`  <- Paste its output here.
 - Start Node RED, and see of the issue has gone.
 
 8.1 included driver version  10.16, so indeed odd

**Comment by marcus-j-davies** [comment]
Oh hang on @AlCalzone .

The system error log was prior to updating to 8.1 so that would explain it  🤣.
Will see what the above brings anyhow.

@ReziioAdmin 
if you could enable Logging after the update, and include any Node RED crash log output also - if applicable

**Comment by ReziioAdmin** [comment]
Still crashes.  NR system log->
May 04 11:39:16 xxx-xxxx Node-RED[7825]: 4 May 11:39:16 - [error] ZWaveError: The controller is not yet ready! (ZW0103)
May 04 11:39:16 xxx-xxxxNode-RED[7825]:     at Driver.get controller [as controller] (/home/pi/.node-red/node_modules/zwave-js/src/lib/driver/Driver.ts:709:10)
May 04 11:39:16 xxx-xxx Node-RED[7825]:     at Driver.get ownNodeId [as ownNodeId] (/home/pi/.node-red/node_modules/zwave-js/src/lib/driver/Driver.ts:753:15)
May 04 11:39:16 rosedale-apt-multi-N200 Node-RED[7825]:     at BridgeApplicationCommandRequest.toLogEntry (/home/pi/.node-red/node_modules/zwave-js/src/lib/serialapi/application/BridgeApplicationCommandRequest.ts:114:39)
May 04 11:39:16 xxx-xxx Node-RED[7825]:     at DriverLogger.logMessage (/home/pi/.node-red/node_modules/zwave-js/src/lib/log/Driver.ts:127:28)
May 04 11:39:16 xxx-xxx Node-RED[7825]:     at Driver.serialport_onData (/home/pi/.node-red/node_modules/zwave-js/src/lib/driver/Driver.ts:2913:22)
May 04 11:39:16 xxx-xxx systemd[1]: nodered.service: Main process exited, code=exited, status=1/FAILURE
May 04 11:39:16 xxx-xxx systemd[1]: nodered.service: Failed with result 'exit-code'.
May 04 11:39:16 xxx-xxx systemd[1]: nodered.service: Consumed 23.579s CPU time.
May 04 11:39:36 xxx-xxx systemd[1]: nodered.service: Scheduled restart job, restart counter is at 13.

**Comment by marcus-j-davies** [comment]
@AlCalzone 

Unless there is some really odd thing going on with versioning, there still seems to be some unhandled exception 🤷 

```
2023-05-04T15:39:12.652Z DRIVER   version 10.17.1
2023-05-04T15:39:12.653Z DRIVER   
2023-05-04T15:39:12.653Z DRIVER   starting driver...
2023-05-04T15:39:12.700Z DRIVER   opening serial port /dev/ttyUSB0
2023-05-04T15:39:14.232Z DRIVER   serial port opened
2023-05-04T15:39:14.235Z SERIAL Â» 0x15                                                                 (1 bytes)
2023-05-04T15:39:16.211Z SERIAL Â« 0x010b00a800011202984000c055                                        (13 bytes)
2023-05-04T15:39:16.227Z SERIAL Â» [ACK]                                                                   (0x06)
------------> Unhandled Exeption Here (Crash Log Below) <------------
2023-05-04T15:39:51.823Z NDERED   [options] [interview.queryAllUserCodes] Disabled
2023-05-04T15:39:51.835Z NDERED   [options] [disableOptimisticValueUpdate] Disabled
2023-05-04T15:39:51.837Z NDERED   [options] [enableSoftReset] Disabled
2023-05-04T15:39:51.838Z NDERED   [options] [storage.cacheDir] /home/pi/.node-red/zwave-js-cache
2023-05-04T15:39:51.840Z NDERED   [options] [storage.throttle] normal
2023-05-04T15:39:51.842Z NDERED   [options] [securityKeys.S0_Legacy] Encryption key provided          [16 bytes]
2023-05-04T15:39:51.845Z NDERED   [options] [securityKeys.S2_Unauthenticated] Encryption key provided [16 bytes]
2023-05-04T15:39:51.848Z NDERED   [options] [securityKeys.S2_Authenticated] Encryption key provided   [16 bytes]
2023-05-04T15:39:51.849Z NDERED   [options] [securityKeys.S2_AccessControl] Encryption key provided   [16 bytes]
2023-05-04T15:39:51.852Z NDERED   [options] [preferences.scales.temperature] 0x00
2023-05-04T15:39:51.853Z NDERED   [options] [preferences.scales.humidity] 0x00
2023-05-04T15:39:51.855Z NDERED   [FWUS] No key provided - Service may fail!
```

Crash Log

```
May 04 11:39:16 xxx-xxxx Node-RED[7825]: 4 May 11:39:16 - [error] ZWaveError: The controller is not yet ready! (ZW0103)
May 04 11:39:16 xxx-xxxxNode-RED[7825]:     at Driver.get controller [as controller] (/home/pi/.node-red/node_modules/zwave-js/src/lib/driver/Driver.ts:709:10)
May 04 11:39:16 xxx-xxx Node-RED[7825]:     at Driver.get ownNodeId [as ownNodeId] (/home/pi/.node-red/node_modules/zwave-js/src/lib/driver/Driver.ts:753:15)
May 04 11:39:16 rosedale-apt-multi-N200 Node-RED[7825]:     at BridgeApplicationCommandRequest.toLogEntry (/home/pi/.node-red/node_modules/zwave-js/src/lib/serialapi/application/BridgeApplicationCommandRequest.ts:114:39)
May 04 11:39:16 xxx-xxx Node-RED[7825]:     at DriverLogger.logMessage (/home/pi/.node-red/node_modules/zwave-js/src/lib/log/Driver.ts:127:28)
May 04 11:39:16 xxx-xxx Node-RED[7825]:     at Driver.serialport_onData (/home/pi/.node-red/node_modules/zwave-js/src/lib/driver/Driver.ts:2913:22)
May 04 11:39:16 xxx-xxx systemd[1]: nodered.service: Main process exited, code=exited, status=1/FAILURE
May 04 11:39:16 xxx-xxx systemd[1]: nodered.service: Failed with result 'exit-code'.
May 04 11:39:16 xxx-xxx systemd[1]: nodered.service: Consumed 23.579s CPU time.
May 04 11:39:36 xxx-xxx systemd[1]: nodered.service: Scheduled restart job, restart counter is at 13.
```

@ReziioAdmin 

If providing logs in-line (not as an attached file), can you put them between code fences  - just makes it easier to read 😇 

````
```
Log Here
```
````

**Comment by AlCalzone** [comment]
Ok now it looks like a different error.

Side note: You seem to have some nodes reporting pretty frequently if this happens reproducibly in the few seconds it takes to initialize the driver.
Might want to look into that and tone it down. This is probably not good for mesh reliability.

**Comment by ReziioAdmin** [comment]
Thank you for theses inputs.  I will use the code fences going forward.  

A few other pieces of information which may help.  
I have over 50 hubs running the same hardware and identical NR flows and have not had this before when NR just won't restart.   There is an ongoing issue where Zwave-JS seems to force a NR restart on a larger network whenever a new device is joined.

I have a suspicion that the error on the particular device is hardware related.  Possibly the USB port or the dongle have a some issue.  I am going to reload the installation onto a new Hub and see if this resolves anything
